/*
 * FileSuplier.java
 *
 * Created on 07 Jun 09, 21:27:11
 */

package apotik;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;

/**
 *
 * @author Ryan
 */
public class FileSuplier extends javax.swing.JInternalFrame {
    String nmr;
    boolean data;
    DefaultTableModel tabMode;
    int n = 0;
    Object row[] = {"No","Kode","Nama","Alamat","Telepon","CP","Telp. CP"};
    boolean edit[] = {false,false,false,false,false,false,false};
    /** Creates new form FileSuplier */
    public FileSuplier() {
        initComponents();
        tampilTabel();
        atur(false);
        if(tabMode.getRowCount() > 0)
        {
            tampilTeks(0);
            cari(true);
        } else {
            btnHapus.setEnabled(false);
            btnEdit.setEnabled(false);
            cari(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSup = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSemua = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelpCp = new javax.swing.JTextField();

        setTitle("File Data Supplier");

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.gif"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setName("btnTambah"); // NOI18N
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        btnTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTambahKeyPressed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setName("btnEdit"); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        btnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEditKeyPressed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setName("btnSimpan"); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setName("btnHapus"); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblSup.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblSup.setEnabled(false);
        tblSup.setName("tblSup"); // NOI18N
        jScrollPane2.setViewportView(tblSup);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari.gif"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.gif"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setName("btnClose"); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        btnClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCloseKeyPressed(evt);
            }
        });

        jLabel7.setText("User :");
        jLabel7.setName("jLabel7"); // NOI18N

        lblUser.setText("user");
        lblUser.setName("lblUser"); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-f-sup.jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.setName("jLabel8"); // NOI18N

        btnSemua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari.gif"))); // NOI18N
        btnSemua.setText("Semua");
        btnSemua.setName("btnSemua"); // NOI18N
        btnSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemuaActionPerformed(evt);
            }
        });
        btnSemua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSemuaKeyPressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel9.setText("Kode Supplier");
        jLabel9.setName("jLabel9"); // NOI18N

        txtTelp.setDocument(new atribut().angka());
        txtKode.setEnabled(false);
        txtKode.setName("txtKode"); // NOI18N
        txtKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeKeyPressed(evt);
            }
        });

        txtTelp.setDocument(new atribut().angka());
        txtTelp.setName("txtTelp"); // NOI18N
        txtTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelpKeyPressed(evt);
            }
        });

        jLabel2.setText("Nama Supplier");
        jLabel2.setName("jLabel2"); // NOI18N

        txtNama.setName("txtNama"); // NOI18N
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
        });

        jLabel3.setText("Alamat");
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtAlamat.setColumns(20);
        txtAlamat.setLineWrap(true);
        txtAlamat.setName("txtAlamat"); // NOI18N
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlamatKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlamat);

        jLabel4.setText("Telepon");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Contact Person");
        jLabel5.setName("jLabel5"); // NOI18N

        txtCp.setName("txtCp"); // NOI18N
        txtCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpKeyPressed(evt);
            }
        });

        jLabel6.setText("Telp. CP");
        jLabel6.setName("jLabel6"); // NOI18N

        txtTelpCp.setDocument(new atribut().angka());
        txtTelpCp.setName("txtTelpCp"); // NOI18N
        txtTelpCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelpCpKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCp, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txtTelpCp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelpCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnCari)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSemua)
                            .addGap(255, 255, 255)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblUser)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClose))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnTambah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnHapus))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCari, btnSemua});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEdit, btnHapus, btnSimpan, btnTambah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(btnSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lblUser)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCari, btnSemua});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int respon = JOptionPane.showConfirmDialog(this,
                "Apakah data akan dihapus?\n"+
                "Kode : "+ txtKode.getText()+"\n" +
                "Nama : "+txtNama.getText()+"\n" +
                "Telp : "+txtTelp.getText(),
                "Penghapusan Data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (respon == 0) {
            try
            {
                Connection con = new sqlConfig().db();
                Statement stmt = con.createStatement();
                String sql = "DELETE FROM supplier WHERE kdsup ='" + txtKode.getText() + "'";
                stmt.executeUpdate(sql);
                stmt.close();
                con.close();
                JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus","Hapus Data",2);
                tampilTabel();
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus","Hapus Data",2);
            }
        }
        if(tabMode.getRowCount() > 0) {tampilTeks(0);cari(true);} else {btnHapus.setEnabled(false);btnEdit.setEnabled(false);kosong();cari(false);}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        carian();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        tambah();
        MainMenu.menu(true);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemuaActionPerformed
        // TODO add your handling code here:
        tampilTabel();
}//GEN-LAST:event_btnSemuaActionPerformed

    private void btnSemuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSemuaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) tampilTabel();
}//GEN-LAST:event_btnSemuaKeyPressed

    private void btnTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTambahKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) tambah();
    }//GEN-LAST:event_btnTambahKeyPressed

    private void btnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEditKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) edit();
    }//GEN-LAST:event_btnEditKeyPressed

    private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) carian();
    }//GEN-LAST:event_btnCariKeyPressed

    private void btnCloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCloseKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){tambah();MainMenu.menu(true); dispose();}
    }//GEN-LAST:event_btnCloseKeyPressed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) simpan();
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void txtTelpCpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelpCpKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){btnSimpan.requestFocus();}
}//GEN-LAST:event_txtTelpCpKeyPressed

    private void txtCpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){txtTelpCp.requestFocus();}
}//GEN-LAST:event_txtCpKeyPressed

    private void txtTelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelpKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){txtCp.requestFocus();}
}//GEN-LAST:event_txtTelpKeyPressed

    private void txtAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)txtTelp.requestFocus();
}//GEN-LAST:event_txtAlamatKeyPressed

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)txtAlamat.requestFocus();
}//GEN-LAST:event_txtNamaKeyPressed

    private void txtKodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeKeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_txtKodeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSemua;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    protected static javax.swing.JLabel lblUser;
    private javax.swing.JTable tblSup;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCp;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTelpCp;
    // End of variables declaration//GEN-END:variables

    void cari(boolean ft)
    {
        btnCari.setEnabled(ft);
    }

    void atur(boolean ft)
	{
		txtNama.setEnabled(ft);
		txtAlamat.setEnabled(ft);
		txtTelp.setEnabled(ft);
        txtCp.setEnabled(ft);
		txtTelpCp.setEnabled(ft);
		btnSimpan.setEnabled(ft);
        btnHapus.setEnabled(!ft);
		btnTambah.setEnabled(!ft);
		btnEdit.setEnabled(!ft);
	}

	void kosong()
	{
		txtKode.setText("");
        txtNama.setText("");
		txtAlamat.setText("");
		txtTelp.setText("");
        txtCp.setText("");
		txtTelpCp.setText("");
	}

    void proses(String sql)
    {
        tblKosong();
        int a=1;
        try
        {
            Connection con = new sqlConfig().db();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next())
            {
                String Kode = rs.getString(1);
                String Nama = rs.getString(2);
                String Alamat = rs.getString(3);
                String Telp = rs.getString(4);
                String Cp = rs.getString(5);
                String TelpCp = rs.getString(6);
                String no = Integer.toString(a);
                String dt[] = {no,Kode,Nama,Alamat,Telp,Cp,TelpCp};
                tabMode.addRow(dt);
                a++;
            }
            stmt.close();
        }
        catch(SQLException e)
        {}
    }

    void tampilTabel()
    {
        String sql = "SELECT * FROM supplier ORDER BY kdsup ASC";
        tabMode = new DefaultTableModel(null, row);
        tblSup.setModel(tabMode);
        proses(sql);
    }

    public void tblKosong()
    {
        int rw = tabMode.getRowCount();
        for(int i=0; i<rw; i++)
        {
            tabMode.removeRow(rw);
        }
    }

    void tampilTeks(int row)
    {
        String kode = tabMode.getValueAt(row, 1).toString();
        String nama = tabMode.getValueAt(row, 2).toString();
        String alamat = tabMode.getValueAt(row, 3).toString();
        String telp = tabMode.getValueAt(row, 4).toString();
        String cp = tabMode.getValueAt(row, 5).toString();
        String telpcp = tabMode.getValueAt(row, 6).toString();
        txtKode.setText(kode);
        txtNama.setText(nama);
		txtAlamat.setText(alamat);
		txtTelp.setText(telp);
        txtCp.setText(cp);
		txtTelpCp.setText(telpcp);
    }

    void tambah()
    {
        String baru = null;
        if (btnTambah.getText().compareTo("Tambah") == 0) {
            atur(true);
            btnTambah.setEnabled(true);
            kosong();
            data = true;
            btnTambah.setText("Batal");
            txtNama.requestFocus();

            String sql = "SELECT MAX(kdsup) FROM supplier";

            try
            {
                Connection con = new sqlConfig().db();
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                if(rs.next())
                {
                    baru = Integer.toString(Integer.parseInt(rs.getString(1).substring(3, 5)) + 1);
                }
            }
            catch(Exception e)
            {
                baru = "01";
            }

            if(baru.length() == 1) {
                baru = "0" + baru;
            }

            nmr = "SUP" + baru;
            txtKode.setText(nmr);

        } else if (btnTambah.getText().compareTo("Tambah") != 0) {
            atur(false);
            btnTambah.setText("Tambah");
            kosong();
            if(tabMode.getRowCount() > 0) {tampilTeks(0);cari(true);} else {btnHapus.setEnabled(false);btnEdit.setEnabled(false);cari(false);}
        }
    }

    void edit()
    {
        if (btnEdit.getText().compareTo("Edit") == 0) {
            atur(true);
            btnEdit.setEnabled(true);
            txtNama.setEnabled(false);
            data = false;
            btnEdit.setText("Batal");
            txtNama.requestFocus();
        } else if (btnEdit.getText().compareTo("Edit") != 0) {
            atur(false);
            btnEdit.setText("Edit");
            tampilTeks(n);
        }
    }

    void carian()
    {
        tampilTabel();
        String cari = JOptionPane.showInputDialog("Masukkan Kode Supplier Atau Nama Supplier");
        String sql = "SELECT * FROM supplier WHERE kdsup LIKE '%" + cari + "%' OR nmsup LIKE '%" + cari + "%'";
        tabMode = new DefaultTableModel(null, row);
        tblSup.setModel(tabMode);
        proses(sql);
        if(tabMode.getRowCount() <= 0)
        {
            if(cari==null || cari.isEmpty()==true){cari="";JOptionPane.showMessageDialog(null, "Pencarian dibatalkan");}
            else JOptionPane.showMessageDialog(null, "Data Dengan Pencarian [" + cari + "] Tidak Ditemukan");
            tampilTabel();
            tampilTeks(0);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Ditemukan Data Dengan Pencarian [" + cari + "]");
            tampilTeks(0);
        }
    }

    void simpan()
    {
        int respon = JOptionPane.showConfirmDialog(this,
                "Apakah data akan dimasukkan ke database?\n"+
                "Kode : "+ txtKode.getText()+"\n" +
                "Nama : "+txtNama.getText()+"\n" +
                "Telp : "+txtTelp.getText()+"\n" +
                "Contact Person : "+txtCp.getText()+"\n" +
                "Telp. Contact Person : "+txtTelpCp.getText()+"\n",
                "Penambahan Data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (respon == 0) {
            if(data == true) {
                try {
                    Connection con = new sqlConfig().db();
                    Statement stmt = con.createStatement();
                    String sql = "INSERT INTO supplier VALUES ('"+txtKode.getText()+"','"+txtNama.getText()+"','"+txtAlamat.getText().toString()+"','"+txtTelp.getText()+"','"+txtCp.getText()+"','"+txtTelpCp.getText()+"')";
                    stmt.executeUpdate(sql);
                    stmt.close();
                    con.close();
                    JOptionPane.showMessageDialog(this,"Data Berhasil Ditambah","Tambah Data",2);
                    tampilTabel();
                    if(tabMode.getRowCount() > 0) {tampilTeks(0);cari(true);} else {btnHapus.setEnabled(false);btnEdit.setEnabled(false);cari(false);}
                } catch(SQLException e) {
                    JOptionPane.showMessageDialog(this,"Data Gagal Ditambah","Tambah Data",2);
                }
                btnTambah.setText("Tambah");
            } else if(data == false) {
                try {
                    Connection con = new sqlConfig().db();
                    Statement stmt = con.createStatement();
                    String sql = "UPDATE Supplier SET nmsup = '" + txtNama.getText() + "', almtSup ='" + txtAlamat.getText()  + "', tlpSup ='" + txtTelp.getText() + "', cp ='" + txtCp.getText() + "', cptelp ='" + txtTelpCp.getText() + "' WHERE kdsup ='" + txtKode.getText() + "'";
                    stmt.executeUpdate(sql);
                    stmt.close();
                    con.close();
                    JOptionPane.showMessageDialog(this,"Data Berhasil Diupdate","Update Data",2);
                    tampilTabel();
                    if(tabMode.getRowCount() > 0) {tampilTeks(0);cari(true);} else {btnHapus.setEnabled(false);btnEdit.setEnabled(false);cari(false);}
                } catch(SQLException e) {
                    JOptionPane.showMessageDialog(this,"Data Gagal Diupdate","Update Data",2);
                }
                btnEdit.setText("Edit");
            }
            atur(false);
            tampilTeks(0);
        }
    }
}
