/*
 * FileUserDetail.java
 *
 * Created on 11 Jun 09, 4:29:31
 */

package apotik;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author Ryan
 */
public class FileUserDetail extends javax.swing.JDialog {

    /** Creates new form FileUserDetail */
    public FileUserDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnClose = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtTempat = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        btnPassword = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rA = new javax.swing.JRadioButton();
        rK = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Managemen User");

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.gif"))); // NOI18N
        btnClose.setText("Close");
        btnClose.setName("btnClose"); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setName("btnEdit"); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        btnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEditKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("Nama Pengguna");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Nama");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Alamat");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("Tempat Lahir");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Tanggal Lahir");
        jLabel5.setName("jLabel5"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtAlamat.setLineWrap(true);
        txtAlamat.setWrapStyleWord(true);
        txtAlamat.setEnabled(false);
        txtAlamat.setName("txtAlamat"); // NOI18N
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlamatKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlamat);

        txtTempat.setEnabled(false);
        txtTempat.setName("txtTempat"); // NOI18N
        txtTempat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTempatKeyReleased(evt);
            }
        });

        txtTgl.setEnabled(false);
        txtTgl.setName("txtTgl"); // NOI18N
        txtTgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTglKeyPressed(evt);
            }
        });

        txtUser.setEnabled(false);
        txtUser.setName("txtUser"); // NOI18N
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });

        txtNama.setEnabled(false);
        txtNama.setName("txtNama"); // NOI18N
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
        });

        btnPassword.setText("Ganti Password");
        btnPassword.setEnabled(false);
        btnPassword.setName("btnPassword"); // NOI18N
        btnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordActionPerformed(evt);
            }
        });
        btnPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPasswordKeyPressed(evt);
            }
        });

        jLabel6.setText("Password");
        jLabel6.setName("jLabel6"); // NOI18N

        txtPassword.setEnabled(false);
        txtPassword.setName("txtPassword"); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        jLabel7.setText("Format : yyyy-mm-dd");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("Telepon");
        jLabel8.setName("jLabel8"); // NOI18N

        txtTelp.setEnabled(false);
        txtTelp.setName("txtTelp"); // NOI18N
        txtTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelpKeyReleased(evt);
            }
        });

        jLabel9.setText("Status");
        jLabel9.setName("jLabel9"); // NOI18N

        buttonGroup1.add(rA);
        rA.setText("Admin");
        rA.setEnabled(false);
        rA.setName("rA"); // NOI18N
        rA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAActionPerformed(evt);
            }
        });
        rA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rAKeyPressed(evt);
            }
        });

        buttonGroup1.add(rK);
        rK.setText("Kasir");
        rK.setEnabled(false);
        rK.setName("rK"); // NOI18N
        rK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rKActionPerformed(evt);
            }
        });
        rK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rKKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rKKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(btnPassword))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTempat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rK)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(rA)
                    .addComponent(rK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(btnPassword))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        tutup(btnClose.getText());
        FileUser.all();
        FileUser.teks();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        proses(btnEdit.getText());
}//GEN-LAST:event_btnEditActionPerformed

    private void txtAlamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)txtTelp.requestFocus();
}//GEN-LAST:event_txtAlamatKeyReleased

    private void txtTempatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempatKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)txtTgl.requestFocus();
}//GEN-LAST:event_txtTempatKeyReleased

    private void txtTglKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTglKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)btnEdit.requestFocus();
}//GEN-LAST:event_txtTglKeyPressed

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)txtPassword.requestFocus();
}//GEN-LAST:event_txtUserKeyReleased

    private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)txtAlamat.requestFocus();
}//GEN-LAST:event_txtNamaKeyReleased

    private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
        // TODO add your handling code here:
        pwd();
}//GEN-LAST:event_btnPasswordActionPerformed

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)txtNama.requestFocus();
}//GEN-LAST:event_txtPasswordKeyReleased

    private void txtTelpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelpKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)rA.requestFocus();
}//GEN-LAST:event_txtTelpKeyReleased

    private void rAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAActionPerformed
        // TODO add your handling code here:
        txtTempat.requestFocus();
}//GEN-LAST:event_rAActionPerformed

    private void rKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rKActionPerformed
        // TODO add your handling code here:
        txtTempat.requestFocus();
}//GEN-LAST:event_rKActionPerformed

    private void rKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rKKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)txtTempat.requestFocus();
}//GEN-LAST:event_rKKeyReleased

    private void btnPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)pwd();
    }//GEN-LAST:event_btnPasswordKeyPressed

    private void btnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEditKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)proses(btnEdit.getText());
    }//GEN-LAST:event_btnEditKeyPressed

    private void rAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rAKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)rK.requestFocus();
    }//GEN-LAST:event_rAKeyPressed

    private void rKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rKKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)txtTempat.requestFocus();
    }//GEN-LAST:event_rKKeyPressed

    /**
    * @param args the command line arguments
    */
    /**public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FileUserDetail dialog = new FileUserDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnClose;
    protected javax.swing.JButton btnEdit;
    protected javax.swing.JButton btnPassword;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JRadioButton rA;
    protected javax.swing.JRadioButton rK;
    protected javax.swing.JTextArea txtAlamat;
    protected javax.swing.JTextField txtNama;
    protected javax.swing.JTextField txtPassword;
    protected javax.swing.JTextField txtTelp;
    protected javax.swing.JTextField txtTempat;
    protected javax.swing.JTextField txtTgl;
    protected javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    void pwd()
    {
        String a = JOptionPane.showInputDialog(this,"Masukkan Password Baru");
        String b = JOptionPane.showInputDialog(this,"Ulangi Password Baru");
        if(a==null || a.isEmpty()==true || b==null || b.isEmpty()==true)
        {
           a="";b="";
           JOptionPane.showMessageDialog(this, "Proses dibatalkan","Ganti Password",JOptionPane.WARNING_MESSAGE);
        }
        else if(a.compareTo(b)==0 && a.length()<=10)
        {
            try
            {
                Connection con = new sqlConfig().db();
                Statement stmt = con.createStatement();
                stmt.executeUpdate("UPDATE user SET pwd=MD5('"+a+"') WHERE idUser='"+txtUser.getText()+"'");
                JOptionPane.showMessageDialog(this, "Proses Berhasil.\nPassword Baru "+a,"Ganti Password",JOptionPane.INFORMATION_MESSAGE);
                txtPassword.setText(a);
            }
            catch(SQLException e)
            {JOptionPane.showMessageDialog(this, "Proses Gagal."+a,"Ganti Password",JOptionPane.WARNING_MESSAGE);}
        }
        else
        {
            if(a.compareTo(b) != 0)
                JOptionPane.showMessageDialog(this, "Kedua Password Berbeda.\nProses Dibatalkan.","Ganti Password",JOptionPane.WARNING_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "Panjang Karakter Lebih Dari 10 Tidak Diizinkan.\nProses Dibatalkan.","Ganti Password",JOptionPane.WARNING_MESSAGE);
        }
    }

    void aktif(boolean ft)
    {
        txtAlamat.setEnabled(ft);
        txtNama.setEnabled(ft);
        txtTelp.setEnabled(ft);
        txtTempat.setEnabled(ft);
        txtTgl.setEnabled(ft);
        rA.setEnabled(ft);
        rK.setEnabled(ft);
        btnPassword.setEnabled(ft);
    }

    void proses(String s)
    {
        int a = 0;
        if(s.compareTo("Edit")==0)
        {
            aktif(true);
            txtUser.setEnabled(false);
            btnEdit.setText("Simpan");
            btnClose.setText("Batal");
        }
        else if(s.compareTo("Simpan")==0)
        {
            if(rA.isSelected()) {a =1;}
            else if(rK.isSelected()) {a =0;}
            try
            {
                String sql = "UPDATE user SET nmUser='"+txtNama.getText()+"', almtUser='"+txtAlamat.getText()+"', tlpUser='"+txtTelp.getText()+
                        "', tmplahir='"+txtTempat.getText()+"', tgllahir='"+txtTgl.getText()+"', status="+ Integer.toString(a) +
                        " WHERE idUser='"+txtUser.getText()+"'";
                Connection con = new sqlConfig().db();
                Statement stmt = con.createStatement();
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Proses Berhasil","managemen User",JOptionPane.INFORMATION_MESSAGE);
                aktif(false);
                btnEdit.setText("Edit");
                btnClose.setText("Close");
            }
            catch(SQLException e)
            {JOptionPane.showMessageDialog(this, "Proses Berhasil","managemen User",JOptionPane.WARNING_MESSAGE);}
        }
        else if(s.compareTo("Tambah")==0)
        {
            aktif(false);
            btnEdit.setText("Edit");
            btnClose.setText("Close");
            txtUser.setEnabled(false);
            txtPassword.setEnabled(false);
            if(rA.isSelected()) {a =1;}
            else if(rK.isSelected()) {a =0;}

            if(txtUser.getText().length()>3 || txtPassword.getText().length() >10)
            {
                if(txtUser.getText().length() > 3)
                {
                    JOptionPane.showMessageDialog(this, "Nama User Maksimal 3 Karakter",getTitle(),1);
                    txtUser.requestFocus();
                    txtUser.selectAll();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Password Maksimal 10 Karakter",getTitle(),1);
                    txtPassword.requestFocus();
                    txtPassword.selectAll();
                }
            }
            else
            {
            String sql = "INSERT INTO user VALUES ('"+txtUser.getText()+"',MD5('"+txtPassword.getText()+"'),'"+txtNama.getText()+
                    "','"+txtTempat.getText()+"','"+txtTgl.getText()+"','"+txtAlamat.getText()+"','"+txtTelp.getText()+"',"+
                    Integer.toString(a) +",0)";
            try
            {
                Connection con = new sqlConfig().db();
                Statement stmt = con.createStatement();
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Proses Berhasil","Managemen User",JOptionPane.INFORMATION_MESSAGE);
                aktif(false);
                btnEdit.setText("Edit");
                btnClose.setText("Close");
            }
            catch(SQLException e)
            {JOptionPane.showMessageDialog(this, "Proses Gagal","Managemen User",JOptionPane.WARNING_MESSAGE);}
            dispose();
            }
        }
    }

    void tutup(String t)
    {
        if(t.compareTo("Close")==0)
        {
            dispose();
            FileUser.all();
        }
        aktif(false);
        txtUser.setEnabled(false);
        txtPassword.setEnabled(false);
        btnEdit.setText("Edit");
        btnClose.setText("Close");
    }
}
