/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LapObat.java
 *
 * Created on 29 Mei 09, 21:05:21
 */

package apotik;

import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.HashMap;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ryan
 */
public class LapObat extends javax.swing.JInternalFrame {

    /** Creates new form LapObat */
    public LapObat() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPilih = new javax.swing.JComboBox();
        cmbKode = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnTutup = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Laporan Data Obat");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilih Mode Laporan"));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("Pilihan Obat");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Kode Supplier");
        jLabel2.setName("jLabel2"); // NOI18N

        cmbPilih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua", "Berdasarkan Supplier" }));
        cmbPilih.setName("cmbPilih"); // NOI18N
        cmbPilih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPilihItemStateChanged(evt);
            }
        });

        cmbKode.setName("cmbKode"); // NOI18N
        cmbKode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKodeItemStateChanged(evt);
            }
        });

        jLabel3.setText("Nama Supplier");
        jLabel3.setName("jLabel3"); // NOI18N

        txtNama.setEnabled(false);
        txtNama.setName("txtNama"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbKode, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPilih, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.gif"))); // NOI18N
        btnTutup.setMnemonic('T');
        btnTutup.setText("Tutup");
        btnTutup.setName("btnTutup"); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        btnTutup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTutupKeyPressed(evt);
            }
        });

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.gif"))); // NOI18N
        btnCetak.setMnemonic('C');
        btnCetak.setText("Cetak");
        btnCetak.setName("btnCetak"); // NOI18N
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        btnCetak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCetakKeyPressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-L-Obat.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTutup))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCetak, btnTutup});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak)
                    .addComponent(btnTutup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCetak, btnTutup});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPilihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPilihItemStateChanged
        // TODO add your handling code here:
        if(cmbPilih.getSelectedIndex()==1)
        {
            cmbKode.setEnabled(true);
        }
        else cmbKode.setEnabled(false);
    }//GEN-LAST:event_cmbPilihItemStateChanged

    private void cmbKodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKodeItemStateChanged
        // TODO add your handling code here:
        try
        {
            Connection con = new sqlConfig().db();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT nmsup FROM supplier WHERE kdsup LIKE '"+cmbKode.getSelectedItem().toString()+"'");
            rs.next();
            txtNama.setText(rs.getString("nmsup"));
        }
        catch(SQLException e){}
    }//GEN-LAST:event_cmbKodeItemStateChanged

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        MainMenu.menu(true);
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnTutupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTutupKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){MainMenu.menu(true); dispose();}
    }//GEN-LAST:event_btnTutupKeyPressed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        cetak();
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnCetakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCetakKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) cetak();
    }//GEN-LAST:event_btnCetakKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTutup;
    protected javax.swing.JComboBox cmbKode;
    protected javax.swing.JComboBox cmbPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    void cetak()
    {
        String cetak[] = {"Cetak Layar","Cetak Kertas"};
        int z = JOptionPane.showOptionDialog(this, "Silahkan Pilih Mode Cetakan", getTitle(), 0, JOptionPane.QUESTION_MESSAGE, null, cetak, cetak[0]);
        if(z==0 || z==1)
        {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Properties systemProp = System.getProperties();

            // Ambil current dir
            String currentDir = systemProp.getProperty("user.dir");

            if(cmbKode.isEnabled())
            {
                Connection con = new sqlConfig().db();
                HashMap<String, Object> parameter = new HashMap<String, Object>();
                parameter.put("user", Login.nama);
                parameter.put("supplier", "("+cmbKode.getSelectedItem().toString()+") "+txtNama.getText());
                parameter.put("kode", cmbKode.getSelectedItem().toString());
                parameter.put("gambar",currentDir + "/report/logo.jpg");
                if(z==0)
                {
                    try {
                    JasperPrint jasperPrint = JasperFillManager.fillReport(currentDir + "/report/lap_obat_sup.jasper", parameter, con);
                    JasperViewer.viewReport(jasperPrint, false);
                    } catch (JRException ex) {
                    Logger.getLogger(TranJual.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    try {
                    JasperPrint jasperPrint = JasperFillManager.fillReport(currentDir + "/report/lap_obat_sup.jasper", parameter, con);
                    JasperPrintManager.printReport(jasperPrint, true);
                    } catch (JRException ex) {
                    Logger.getLogger(TranJual.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            else
            {
                Connection con = new sqlConfig().db();
                HashMap<String, Object> prs = new HashMap<String, Object>();
                prs.put("user", Login.nama);
                prs.put("gambar",currentDir + "/report/logo.jpg");
                if(z==0)
                {
                    try {
                        JasperPrint jasperPrint = JasperFillManager.fillReport(currentDir + "/report/lap_obat.jasper", prs, con);
                        JasperViewer.viewReport(jasperPrint, false);
                    } catch (JRException ex) {
                        Logger.getLogger(TranJual.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    try {
                        JasperPrint jasperPrint = JasperFillManager.fillReport(currentDir + "/report/lap_obat.jasper", prs, con);
                        JasperPrintManager.printReport(jasperPrint, true);
                    } catch (JRException ex) {
                        Logger.getLogger(TranJual.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            setCursor(Cursor.getDefaultCursor());
            MainMenu.menu(true);
            dispose();
        }
    }
}
