/*
 * Splash.java
 *
 * Created on 29 Mar 09, 21:21:16
 */

package apotik;

/**
 *
 * @author Ryan
 */
public class Splash extends javax.swing.JFrame {

    /** Creates new form Splash */
    public Splash() {
        initComponents();
        setLocationRelativeTo(null);
        int num=0;
        int z[] = {50,60,70,80};
        int i = 1;
		current.setValue(0);
        current.setMaximum(2000);
		current.setStringPainted(true);
		setVisible(true);
		while (num <= 2000)
		{
			current.setValue(num);
			try
			{
				Thread.sleep(250);
			}
			catch (InterruptedException e)
			{
			}
            if(i % 4 == 1)num += z[0]; else
                if(i % 4 == 2)num += z[1]; else
                    if(i % 4 == 3)num += z[2]; else
                        if(i % 4 == 0)num += z[3];
            i++;
		}
		setVisible(false);
        new Login().setVisible(true);
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        current = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apotik Depok | Sistem Informasi Penjualan Obat");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xceples.jpg"))); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(current, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(current, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar current;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
