/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ToolRestore.java
 *
 * Created on 02 Jun 09, 8:54:11
 */

package apotik;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author Mahasiswa
 */
public class ToolRestore extends javax.swing.JInternalFrame {
Properties systemProp = System.getProperties();
String currentDir = systemProp.getProperty("user.home").substring(0,3);

    /** Creates new form ToolRestore */
    public ToolRestore() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcsData = new javax.swing.JFileChooser();
        btnTutup = new javax.swing.JButton();
        btnRestore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Tool Restore Database");

        fcsData.setControlButtonsAreShown(false);
        fcsData.setCurrentDirectory(null);
        fcsData.setName("fcdData"); // NOI18N

        btnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.gif"))); // NOI18N
        btnTutup.setText("Tutup");
        btnTutup.setName("btnTutup"); // NOI18N
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        btnRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.gif"))); // NOI18N
        btnRestore.setText("Restore");
        btnRestore.setName("btnRestore"); // NOI18N
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x-S-Restore.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRestore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTutup))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fcsData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRestore, btnTutup});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fcsData, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestore))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_btnTutupActionPerformed

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
        try {
            // TODO add your handling code here:
            restore();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ToolRestore.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRestoreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestore;
    private javax.swing.JButton btnTutup;
    private javax.swing.JFileChooser fcsData;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    void restore() throws FileNotFoundException
    {
        int len = fcsData.getSelectedFile().toString().length();
        if(fcsData.getSelectedFile().toString().substring(len-3).compareTo("adb")!=0)
        {
            JOptionPane.showMessageDialog(this,"Format Data File bukan apotik database (*.adb)",getTitle(),JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            int z = JOptionPane.showConfirmDialog(this,"Yakin Database Akan Di-Restore.\nDatabase Akan Di-Set Seperti Pada Saat File BackUp Dibuat",getTitle(),JOptionPane.YES_NO_OPTION);
            if(z==0)
            {
            File file = new File(fcsData.getSelectedFile().toString());
            Scanner input = new Scanner(file);
            input.useDelimiter(";");
            while(input.hasNext())
            {
            String txt = input.next();
            try
            {
                Connection con = new sqlConfig().db();
                Statement stmt = con.createStatement();
                stmt.executeUpdate(txt);
            }
            catch(SQLException e){System.out.println(e);}
            }
            input.close();
            JOptionPane.showMessageDialog(this,"Database Telah Di-Restore",getTitle(),JOptionPane.INFORMATION_MESSAGE);
            new atribut().log(Login.nama, "Logout & Keluar Program");
            System.exit(0);
            }
        }
    }
}
